version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: comandasbar_db
    environment:
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: comandabar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: